
GET http://localhost:5000/api/productos
###
POST http://localhost:5000/api/usuario/login 
Content-Type: application/json

{
"usuarioUniandes":"bc.barahona" , "contrasenia": "201812721"
}
### 
POST http://localhost:5000/api/productos 
Content-Type: application/json

{

        "nombre": "prueba1 ",
        "descripcion": "vamos ",
        "proveedor": "tryyy",
        "familia": "familia ",
        "ubicacionEnCubiculo": "abajo ",
        "cantidadTotal": "25",
        "cantidadDisponiblesParaUso": "1",
        "cantidadDisponiblesParaArreglo": "19",
        "cantidadEnUso": "0",
        "cantidadEnArreglo": "5" 

}

###
GET http://localhost:5000/api/usuario 
Content-Type: application/json

{
"usuarioUniandes":"fk.luepke146" , "nombre": "Franz Luepke", "contrasenia": "201210752", "admin": true , "lider": true
}
###
GET http://localhost:5000/api/usuario 

