
GET http://localhost:5000/api/productos/60ef5fe530a37f8f2c4e995a
###
POST http://localhost:5000/api/usuario/login 
Content-Type: application/json

{
"usuarioUniandes":"bc.barahona" , "contrasenia": "201812721"
}
### 
POST http://localhost:5000/api/productos 
Content-Type: application/json

{

        "nombre": "prueba2 ",
        "descripcion": "vamos ",
        "proveedor": "tryyy",
        "familia": "familia ",
        "ubicacionEnCubiculo": "abajo ",
        "cantidadTotal": "25",
        "cantidadDisponiblesParaUso": "1",
        "cantidadDisponiblesParaArreglo": "19",
        "cantidadEnUso": "0",
        "cantidadEnArreglo": "5" 

}

###

POST http://localhost:5000/api/historial
Content-Type: application/json

{
    "cantidad": "5",
    "tipoMovimiento": "desde a a b",
    "responsable": "yo", 
    "fecha": "2021-07-14T22:06:29.156Z" ,  
    "id_producto": "60ef5fe530a37f8f2c4e995a"
        

}
###

GET http://localhost:5000/api/historial/60ef5fe530a37f8f2c4e995a

###
GET http://localhost:5000/api/productos/60f7a58b0d965a6ce4372fee

###
PUT http://localhost:5000/api/productos/mover/60f7a58b0d965a6ce4372fee
Content-Type: application/json

{      
     "id":"60ef71d56e45c11a8c6f126e",
        "desde": "Disponible para arreglar",
        "hasta": "En arreglo",
        "cantidad": "15"
}

####
PUT http://localhost:5000/api/productos/agregar/60f7a58b0d965a6ce4372fee
Content-Type: application/json

{      
     "id":"60ef71d56e45c11a8c6f126e",
        "agregar": "Disponible para arreglar",
        "cantidad": "2"
}
###

PUT http://localhost:5000/api/productos/eliminar/60f7a58b0d965a6ce4372fee
Content-Type: application/json

{      
     "id":"60ef71d56e45c11a8c6f126e",
        "eliminar": "Disponible para arreglar",
        "cantidad": "2"
}

###
GET http://localhost:5000/api/usuario 
Content-Type: application/json

{
"usuarioUniandes":"fk.luepke146" , "nombre": "Franz Luepke", "contrasenia": "201210752", "admin": true , "lider": true
}
###
GET http://localhost:5000/api/usuario 

