###
GET  http://localhost:4000/api/productos

###
DELETE  http://localhost:4000/api/productos

###
POST http://localhost:4000/api/products
Content-Type: application/json

{
    "nombre": "JETSON",
    "cantidad": "5"
}

###
POST http://localhost:4000/api/usuarios
Content-Type: application/json

{
    "usuarioUniandes":"mario.xd" ,
    "nombre": "maria",
    "contrasenia": "123a", 
    "admin": false , 
    "lider": false
}

###
GET http://localhost:4000/api/usuario

###
POST http://localhost:4000/api/usuario/login
Content-Type: application/json

{
    "usuarioUniandes":"mario.xd" ,
    "contrasenia": "123a"

}

###
GET  http://localhost:4000/api/compras

###
POST http://localhost:4000/api/compras
Content-Type: application/json

{
    "nombre": "JETSON",
    "cantidad": "5"
}